<a href="https://colab.research.google.com/github/spannav/PythonDataViz2026/blob/main/HW5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ศุภณัฏฐ์ ปุณมา ID 673020627-7

HW 5 เขียน function คูณ matrix

แล้ว test กับ matrix ขนาด

- (2,3)*(3,2)
- (4,4)*(4,1)
- (2,2)*(2,2)

In [ ]:
import numpy

In [ ]:
def matric_multi(A,B):
    m = len(A) # จำนวนแถว A
    a = len(A[0]) # จำนวนหลัก A
    b = len(B) #จำนวนแถว B
    n = len(B[0]) # จำนวนหลัก B
    C = numpy.zeros((m,n))
    for i in range(m):
        for j in range(n):
            for sum in range(a):
                C[i,j] = C[i,j] + A[i,sum] * B[sum,j]
    return C

In [ ]:
print("______matrix ขนาด (2,3)*(3,2)______")
A = numpy.array([[6, 10, 9],[13, 6, 11]])
B = numpy.array([[14, 8],[12, 7],[10, 11]])
matric_multi(A, B)

______matrix ขนาด (2,3)*(3,2)______


array([[294., 217.],
       [364., 267.]])

In [ ]:
print("______matrix ขนาด (4,4)*(4,1)______")
A = numpy.array([[11, 9, 8, 13],[10, 8, 15, 11],[6, 3, 17, 16],[12, 5, 10, 6]])
B = numpy.array([[8],[14],[2],[11]])
matric_multi(A, B)

______matrix ขนาด (4,4)*(4,1)______


array([[373.],
       [343.],
       [300.],
       [252.]])

In [ ]:
print("______matrix ขนาด (2,2)*(2,2)______")
A = numpy.array([[17, 9],[2, 13]])
B = numpy.array([[6, 12],[18, 4]])
matric_multi(A, B)

______matrix ขนาด (2,2)*(2,2)______


array([[264., 240.],
       [246.,  76.]])